import tkinter as tk 
def saludar(): 
 nombre = entrada.get() 
 edad=entrada2.get()
 etiqueta_resultado.config(text=f"Hola {nombre}, tu tienes {edad} años") 
ventana = tk.Tk() 
ventana.title("Mi primera app gráfica") 
ventana.geometry("400x200") 
ventana.configure(bg="fde977")
etiqueta = tk.Label(ventana, text="Ingresa tu nombre:",bg="fde977") 
etiqueta.pack() 
entrada = tk.Entry(ventana) 
entrada.pack() 
etiqueta = tk.Label(ventana, text="Ingresa tu edad:",bg="fde977") 
etiqueta.pack() 
entrada2 = tk.Entry(ventana) 
entrada2.pack() 
boton = tk.Button(ventana, text="Mostrar saludo", command=saludar) 
boton.pack() 
etiqueta_resultado = tk.Label(ventana, text="",bg="fde977") 
etiqueta_resultado.pack() 
etiqueta_autor = tk.Label(ventana, text="Autor:Camacho Lima Angel Emmanuel",bg="fde977") 
etiqueta_autor.pack()
ventana.mainloop()
